version: '3'

services:
  coordinator:
    depends_on:
      - mysql
    image: ${IMG_NAME}
    container_name: coordinator
    hostname: coordinator
    domainname: ${DOMAIN}
    volumes:
      - ./data/coordinator:/root/shared
    restart: always
    healthcheck:
      test: /etc/init.d/presto status | grep -q 'Running as'
      interval: 5m
      timeout: 10s
      retries: 3
    ports:
      - 8080:8080
    env_file:
      - env/presto.env
      - env/coordinator.env

  worker:
    depends_on:
      - coordinator
    image: ${IMG_NAME}
    domainname: ${DOMAIN}
    volumes:
      - ./data/worker:/root/shared
    restart: always
    healthcheck:
      test: /etc/init.d/presto status | grep -q 'Running as'
      interval: 5m
      timeout: 10s
      retries: 3
    ports:
      - 8080
    environment:
      COORDINATOR: coordinator
    env_file:
      - env/presto.env
      - env/worker.env

  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    domainname: ${DOMAIN}
    volumes:
      - data_mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    env_file:
      - env/mysql.env

volumes:
  data_mysql:
